all:
  children:
    # --- ROOT ACCESS NODES (Hardware & Core Infra) ---
    infrastructure_root:
      vars:
        ansible_user: root
      hosts:
        # Proxmox Hosts
        lucas: { ansible_host: 10.12.5.10 }
        angel: { ansible_host: 10.12.5.12 }
        boo:   { ansible_host: 10.12.5.13 }
        lucky: { ansible_host: 10.12.5.14 }
        # Core Services
        pbs:   { ansible_host: 10.12.5.15 }
        dns1:  { ansible_host: 10.12.5.5 }
        dns2:  { ansible_host: 10.12.5.6 }

    # --- STANDARD USER NODES (Workstations & General VMs) ---
    managed_vms:
      vars:
        ansible_user: demarzo
        ansible_become: true
      hosts:
        ops:   { ansible_host: 10.12.5.20 }
