all:
  children:
    # --- ROOT ACCESS NODES ---
    proxmox:
      vars:
        ansible_user: root
      cluster:
        # Proxmox Hosts
        lucas: { ansible_host: 10.12.5.10 }
        angel: { ansible_host: 10.12.5.12 }
        boo:   { ansible_host: 10.12.5.13 }
      standalone:
        lucky: { ansible_host: 10.12.5.14 }
